


const HistorialReview = [
    { id: 1, libroId: '1', autor: 'Juan Pérez', contenido: 'Una obra excelente, me atrapó desde el inicio.', calificacion: 5 },
    { id: 2, libroId: '1', autor: 'Ana López', contenido: 'Interesante, pero esperaba más del final.', calificacion: 3 },
    { id: 3, libroId: '1', autor: 'Luis Martínez', contenido: 'Un libro que no puedes soltar.', calificacion: 4 },
    { id: 4, libroId: '2', autor: 'Carlos García', contenido: 'Fascinante historia, muy recomendable.', calificacion: 5 },
    { id: 5, libroId: '2', autor: 'María Gómez', contenido: 'Algo repetitivo en ciertas partes.', calificacion: 3 },
    { id: 6, libroId: '2', autor: 'Pedro Ramírez', contenido: 'Espectacular, una experiencia increíble.', calificacion: 5 },
    { id: 7, libroId: '3', autor: 'Laura Sánchez', contenido: 'Me hizo reflexionar profundamente.', calificacion: 5 },
    { id: 8, libroId: '3', autor: 'Fernando Díaz', contenido: 'Demasiado largo para mi gusto.', calificacion: 2 },
    { id: 9, libroId: '3', autor: 'Claudia Herrera', contenido: 'Bien escrito y emocionante.', calificacion: 4 },
    { id: 10, libroId: '4', autor: 'Ricardo Flores', contenido: 'Simplemente perfecto.', calificacion: 5 },
    { id: 11, libroId: '4', autor: 'Sofía Ríos', contenido: 'No me terminó de convencer.', calificacion: 3 },
    { id: 12, libroId: '4', autor: 'Andrea Peña', contenido: 'Una lectura muy entretenida.', calificacion: 4 },
    { id: 13, libroId: '5', autor: 'Tomás Morales', contenido: 'Una historia inolvidable.', calificacion: 5 },
    { id: 14, libroId: '5', autor: 'Lucía Vargas', contenido: 'Pudo haber sido mejor.', calificacion: 3 },
    { id: 15, libroId: '5', autor: 'Miguel Ángel', contenido: 'Una narrativa impecable.', calificacion: 4 },
    { id: 16, libroId: '6', autor: 'Paola Medina', contenido: 'Me transportó a otro mundo.', calificacion: 5 },
    { id: 17, libroId: '6', autor: 'José Suárez', contenido: 'Muy básico, esperaba más.', calificacion: 2 },
    { id: 18, libroId: '6', autor: 'Carolina Álvarez', contenido: 'Llena de sorpresas.', calificacion: 4 },
    { id: 19, libroId: '7', autor: 'Manuel Ortega', contenido: 'Increíblemente profundo y conmovedor.', calificacion: 5 },
    { id: 20, libroId: '7', autor: 'Gloria Fuentes', contenido: 'Demasiados personajes para seguir.', calificacion: 3 },
    { id: 21, libroId: '7', autor: 'Diego Navarro', contenido: 'Una experiencia literaria única.', calificacion: 4 },
    { id: 22, libroId: '8', autor: 'Sergio Hernández', contenido: 'Me encantó la trama y los giros inesperados.', calificacion: 5 },
    { id: 23, libroId: '8', autor: 'Rosa Mendoza', contenido: 'Un poco lento al principio.', calificacion: 3 },
    { id: 24, libroId: '8', autor: 'Eduardo Vargas', contenido: 'Un libro que todos deberían leer.', calificacion: 4 },
    { id: 25, libroId: '9', autor: 'Patricia Ramos', contenido: 'Una obra maestra moderna.', calificacion: 5 },
    { id: 26, libroId: '9', autor: 'Andrés Castro', contenido: 'Interesante, pero no mi estilo.', calificacion: 3 },
    { id: 27, libroId: '9', autor: 'Daniela Ruiz', contenido: 'Estimulante y entretenido.', calificacion: 4 },
    { id: 28, libroId: '10', autor: 'Marcos López', contenido: 'Un viaje inolvidable.', calificacion: 5 },
    { id: 29, libroId: '10', autor: 'Elena Domínguez', contenido: 'Demasiados clichés.', calificacion: 2 },
    { id: 30, libroId: '10', autor: 'Roberto Santos', contenido: 'Un final realmente conmovedor.', calificacion: 4 },
    { id: 31, libroId: '11', autor: 'Silvia Paredes', contenido: 'Una lectura fascinante.', calificacion: 5 },
    { id: 32, libroId: '11', autor: 'Adrián Villalobos', contenido: 'Aburrido en algunas partes.', calificacion: 3 },
    { id: 33, libroId: '11', autor: 'Carmen Salinas', contenido: 'Un desarrollo de personajes impecable.', calificacion: 4 },
    { id: 34, libroId: '12', autor: 'Javier Muñoz', contenido: 'Una joya literaria.', calificacion: 5 },
    { id: 35, libroId: '12', autor: 'Natalia Vera', contenido: 'Confuso en algunas partes.', calificacion: 3 },
    { id: 36, libroId: '12', autor: 'Raúl Sánchez', contenido: 'Espectacular, me sorprendió.', calificacion: 4 },
    { id: 37, libroId: '13', autor: 'Autor 13A', contenido: 'Una historia envolvente.', calificacion: 5 },
    { id: 38, libroId: '13', autor: 'Autor 13B', contenido: 'No es lo que esperaba.', calificacion: 3 },
    { id: 39, libroId: '13', autor: 'Autor 13C', contenido: 'Me encantó el final.', calificacion: 4 },
    { id: 40, libroId: '14', autor: 'Autor 14A', contenido: 'Un gran libro para reflexionar.', calificacion: 5 },
    { id: 41, libroId: '14', autor: 'Autor 14B', contenido: 'Le faltó profundidad.', calificacion: 3 },
    { id: 42, libroId: '14', autor: 'Autor 14C', contenido: 'Una narrativa impresionante.', calificacion: 4 },
    { id: 43, libroId: '15', autor: 'Autor 15A', contenido: 'De lo mejor que he leído.', calificacion: 5 },
    { id: 44, libroId: '15', autor: 'Autor 15B', contenido: 'No me terminó de enganchar.', calificacion: 3 },
    { id: 45, libroId: '15', autor: 'Autor 15C', contenido: 'Interesante y bien escrito.', calificacion: 4 },
    { id: 46, libroId: '16', autor: 'Autor 16A', contenido: 'Una obra maestra.', calificacion: 5 },
    { id: 47, libroId: '16', autor: 'Autor 16B', contenido: 'Más de lo mismo.', calificacion: 2 },
    { id: 48, libroId: '16', autor: 'Autor 16C', contenido: 'Entretenido y cautivador.', calificacion: 4 },
    { id: 49, libroId: '17', autor: 'Autor 17A', contenido: 'Magnífico.', calificacion: 5 },
    { id: 50, libroId: '17', autor: 'Autor 17B', contenido: 'Un poco confuso.', calificacion: 3 },
    { id: 51, libroId: '17', autor: 'Autor 17C', contenido: 'Un libro para recordar.', calificacion: 4 },
    { id: 52, libroId: '18', autor: 'Autor 18A', contenido: 'Espectacular.', calificacion: 5 },
    { id: 53, libroId: '18', autor: 'Autor 18B', contenido: 'Esperaba más.', calificacion: 3 },
    { id: 54, libroId: '18', autor: 'Autor 18C', contenido: 'Un libro impactante.', calificacion: 4 },
    { id: 55, libroId: '19', autor: 'Autor 19A', contenido: 'Una experiencia inolvidable.', calificacion: 5 },
    { id: 56, libroId: '19', autor: 'Autor 19B', contenido: 'No cumplió mis expectativas.', calificacion: 3 },
    { id: 57, libroId: '19', autor: 'Autor 19C', contenido: 'Un libro que todos deberían leer.', calificacion: 4 },
];

export default HistorialReview;